// Todo_Svelte_Project/src/components/TodoList.svelte
<script>
  import TodoItem from './TodoItem.svelte';
  export let todos = [];
  export let onDelete;
  export let onUpdate;
</script>

<ul>
  {#each todos as todo (todo._id)}
    <li>
      <TodoItem {todo} {onDelete} {onUpdate} />
    </li>
  {/each}
</ul>

<style>
  li{
    list-style: none;
    padding-left: 0;
    margin: 0;
  }
  ul{
    padding: 0;
  }
</style>

// Todo_React_Project/src/components/TodoList.jsx
import React from 'react';
import TodoItem from './TodoItem';

const TodoList = ({ todos, onDelete, onUpdate }) => {
  return (
    <div>
      <ul>
        {todos.map(todo => (
          <TodoItem 
            key={todo._id} 
            todo={todo} 
            onDelete={onDelete} 
            onUpdate={onUpdate} 
          />
        ))}
      </ul>
    </div>
  );
};

export default TodoList;
