// Todo_Svelte_Project/src/components/TodoItem.svelte
<script>
  export let todo;
  export let onDelete;
  export let onUpdate;

  function handleCheckbox() {
    onUpdate({ ...todo, done: !todo.done });
  }
</script>

<div class="todo-item">
  <input
    type="checkbox"
    checked={todo.done}
    on:change={handleCheckbox}
  />
  <span class="todo-text" style="text-decoration: {todo.done ? 'line-through' : 'none'}; margin-left: 0.5rem;">
    {todo.text}
  </span>
  <button on:click={() => onDelete(todo._id)} style="margin-left: 1rem;">Delete</button>
</div>

// Todo_React_Project/src/components/TodoItem.jsx
import React from 'react';

const TodoItem = ({ todo, onDelete, onUpdate }) => {
  const handleCheckbox = () => {
    const updatedTodo = { ...todo, done: !todo.done };
    onUpdate(updatedTodo);
  };

  return (
    <div className="todo-item">
      <input
        type="checkbox"
        checked={todo.done}
        onChange={handleCheckbox}
      />
      <span style={{ textDecoration: todo.done ? 'line-through' : 'none' }}>
        {todo.text}
      </span>
      <button class="delButton" onClick={() => onDelete(todo._id)}>Delete</button>
    </div>
  );
};

export default TodoItem;
