// Todo_React_Project/src/components/TodoForm.jsx
import { useState } from 'react';

function TodoForm({ addTodo }) {
  const [inputValue, setInputValue] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    if (inputValue.trim()) {
      addTodo(inputValue);
      setInputValue('');
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        value={inputValue}
        onChange={(e) => setInputValue(e.target.value)}
        placeholder="Add a new todo"
      />
      <button type="submit">Add Todo</button>
    </form>
  );
}

export default TodoForm;

// Todo_Svelte_Project/src/components/TodoForm.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  let inputValue = '';
  const dispatch = createEventDispatcher();

  function handleSubmit(e) {
    e.preventDefault();
    if (inputValue.trim()) {
      dispatch('add', inputValue);
      inputValue = '';
    }
  }
</script>

<form on:submit|preventDefault={handleSubmit}>
  <input
    type="text"
    bind:value={inputValue}
    placeholder="Add a new todo"
  />
  <button type="submit">Add Todo</button>
</form>

<style>
    form{
        margin-bottom: 5%;
    }
</style>
